### ISSUE TITLE
Getting Started (v2): Could not match type String with type JsonDecodeError

### ISSUE THREAD

**Issue by jim108dev** [hendrikniemann/purescript-graphql#28]
Hi! I was trying the tutorial https://hendrikniemann.github.io/purescript-graphql/#/getting_started.

Seems like a dependency has changed.

Steps for reproduction:

1. Init

    ```sh
    mkdir purescript-graphql-example
    cd purescript-graphql-example
    spago --version
    #0.19.0
    spago init
    spago build
    ```

1. `packages.dhall`:

    ```dhall
    let additions =
      { graphql =
        { dependencies =
          [ "argonaut"
          , "console"
          , "control"
          , "effect"
          , "enums"
          , "foldable-traversable"
          , "nullable"
          , "numbers"
          , "prelude"
          , "psci-support"
          , "record"
          , "spec"
          , "string-parsers"
          ]
        , repo = "https://github.com/hendrikniemann/purescript-graphql.git"
        , version = "master"
        }
      }
    ```

    Actually, it is replace `in upstream` with

    ```sh
    let overrides = {=}
    
    let additions = ...

    in  upstream // overrides // additions
    ```

    But I have done this too many times, so no problem there.
    
1. Install

    ```sh
    spago install graphql argonaut maybe either ordered-collections
    spago build
    ```

    ```log
    Error found:
    in module GraphQL.Type
    at .spago/graphql/master/src/GraphQL/Type.purs:19:1 - 19:31 (line 19, column 1 - line 19, column 31)

    Module Data.Variant was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.
    ```

    I guess, `"variant"` should be added to the dependencies, but after that I get

    ```sh
    spago build
    ```

    ```log
    in module GraphQL.Type
    at .spago/graphql/master/src/GraphQL/Type.purs:984:17 - 987:30 (line 984, column 17 - line 987, column 30)

    Could not match type
            
        String
            
    with type
                    
        JsonDecodeError
                    

    while trying to match type Either String
    with type Either JsonDecodeError
    while checking that expression (bind (((...) (...)) hackedCtx)) (\fieldValue ->                 
                                                                    (apply pure) ((...) recValue)
                                                                    )                               
    has type Either JsonDecodeError t0
    in value declaration withInputField

    where t0 is an unknown type    
    ```

**Comment by hendrikniemann** [comment]
Are you using PureScript 0.14?

**Comment by jim108dev** [comment]
Before, no. Today I switched. I can try again with 0.14.

**Comment by jim108dev** [comment]
Now, `spec` and `variant` isn't in the package set anymore.

**Comment by hendrikniemann** [comment]
Okay, seems like I am in the middle of a huge restructuring on my local machine. It fixes the error, but introduces more problems. ~~The best would probably be, if you would start from a package set, that works. Like the one I use with PS 0.13.3 here: https://github.com/hendrikniemann/purescript-graphql-example/blob/master/packages.dhall~~

Actually, I am not sure what the state of the above repo is, I will try to get it running.

**Comment by hendrikniemann** [comment]
I just pushed a new version that includes the mentioned restructuring. It should be compatible with the newest PS 0.13.3 package set. Maybe tomorrow I can try to port to 0.14. This means that the packages are newly distributed. You can check out the [fullstack example](https://github.com/hendrikniemann/purescript-graphql-fullstack-example/tree/master/backend) to see how to use it.

Basically all relevant functions and values are now exported from the root module `GraphQL`.
