### ISSUE TITLE
Can't define recursive or mutually recursive object types

### ISSUE THREAD

**Issue by rndnoise** [hendrikniemann/purescript-graphql#5]
I ran into a snag when trying to define an object of type X that has a field with type X. This will not compile:

```purescript
commentType :: ObjectType Unit Unit
commentType  = objectType
  "Comment"
  (Just "comment")
  { replies: Q.field' (Q.list commentType) -- "The value commentType is not defined here"
      (Just "replies")
      \_ ctx -> pure (Just []) }
```

It also doesn't seem possible to use `Data.Lazy.fix` to achieve this. However, there is a comment in [graphql-91](https://github.com/facebook/graphql/issues/91#issuecomment-197860064) that explains you can do this in JavaScript using a thunk, so I think another wrapper function around `objectType` that has the type of it's last argument as `(Unit -> Record fields)` might do the trick.

**Comment by hendrikniemann** [comment]
Hi, thanks for reporting and spending time with my library! I created this PR #6. What do you think? `objectTypeRec` is quite similar to `maybe'` and does what you proposed.

To work with the package from Github you can clone the repo and use `bower link` to add it to your own project.

**Comment by rndnoise** [comment]
Seems to work well! Didn't require much work to start using it. Thanks! (sorry, previously commented on the wrong thing)
